name: Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'yarn'
    - run: yarn install
    - uses: actions/upload-artifact@v2
      with:
        name: node_modules
        path: node_modules/**/*
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: node_modules
    - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: node_modules
    - run: yarn compile

  package:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: node_modules
    - run: yarn package
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}/CHANGELOG.md
        fail_on_unmatched_files: true
        files: |
          dist/**/*
