name: Package

on:
  push:
    tags:
    - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 #to include tags
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'yarn'
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn package
    - run: mv dist lando-mutagen
    - run: zip -r release.zip lando-mutagen
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}/CHANGELOG.md
        fail_on_unmatched_files: true
        files: release.zip
